name: onuni

services:
  backend:
    build: ./backend
    container_name: backend
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    ports:
      - '3000:3000'
    command: npm run start:dev
  
  frontend:
    build: ./frontend-portal
    container_name: frontend
    env_file:
      - .env.local
    ports:
      - '3001:3001'
    command: npx next start

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - backend_onuni-db:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - '6379:6379'
volumes:
  backend_onuni-db:
    # remove this line if you are using this docker compose for the first time
    external: true 