services:
  backend:
    build: ./backend
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
    command: npm run start
  
  frontend:
    build: ./frontend-portal
    env_file:
      - .env
    ports:
      - '${FRONTEND_PORT}:${FRONTEND_PORT}'
    command: npx next start -p ${FRONTEND_PORT}

  postgres:
    image: postgres:16-alpine
    env_file:
      - .env
    volumes:
      - backend_onuni-db:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
  
  nginx:
    build: ./nginx
    env_file:
      - .env
    ports:
      - '${NGINX_PORT}:${NGINX_PORT}'
    depends_on:
      - backend

volumes:
  backend_onuni-db:
    # remove this line if you are using this docker compose for the first time
    external: true 