name: backend

services:
  nest-backend:
    build: .
    container_name: backend
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    ports:
      - '3000:3000'
    command: npm run start:dev

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - onuni-db:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - '6379:6379'
volumes:
  onuni-db:


